import { Inter } from 'next/font/google';
import { Layout } from 'antd';
import './globals.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Footer, Navbar } from './components';
import StoreProvider from './components/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={(inter.className, 'app')}>
        <StoreProvider>
          <AntdRegistry>
            <header className='navbar'>
              <Navbar />
            </header>
            <main className='main'>
              <Layout>
                <div className='routes'>{children}</div>
                <Footer />
              </Layout>
            </main>
          </AntdRegistry>
        </StoreProvider>
      </body>
    </html>
  );
}
