import { Inter } from 'next/font/google';
import './globals.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout, Typography, Space } from 'antd';
import { Footer, Navbar } from './components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={(inter.className, 'app')}>
        <AntdRegistry>
          <header className='navbar'>
            <Navbar />
          </header>
          <main className='main'>
            <Layout>
              <div className='routes'>{children}</div>
              <Footer />
            </Layout>
          </main>
        </AntdRegistry>
      </body>
    </html>
  );
}
