import { Inter } from 'next/font/google';
import './globals.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout, Typography, Space } from 'antd';
import { Navbar } from './components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AntdRegistry>
          <header className='navbar'>
            <Navbar />
          </header>
          {children}
          <footer></footer>
        </AntdRegistry>
      </body>
    </html>
  );
}
